version: '2'

volumes:
  sandbox_data:
    driver: local

services:

  webserver:
    image: nginx
    working_dir: /application
    volumes:
      - ./application:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - ${NGNIX_BIND_PORT}:80

  php-fpm:
    build: ./docker/php-fpm
    working_dir: /application
    volumes:
      - ./application:/application
      - ./logs/application:/application/storage/logs
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

  database:
    image: mysql:5.7
    ports:
      - 33060:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - sandbox_data:/var/lib/mysql

networks:
  default: